name: flutter_screen_recording_platform_interface
description: A common platform interface for the flutter_screen_recording plugin
version: 1.0.2
# homepage: "https://github.com/Isvisoft/flutter_screen_recording/tree/web/flutter_screen_recording_platform_interface"
publish_to: "none"

environment:
  sdk: ">=2.19.0 <3.0.3"
  flutter: ">=2.5.3"

dependencies:
  flutter:
    sdk: flutter
  # plugin_platform_interface: ^2.0.2
  plugin_platform_interface: ^2.1.4
  # meta: ^1.5.0
  meta: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
